apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: portfolio
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    haproxy-ingress.github.io/backend-protocol: "http"
    haproxy-ingress.github.io/timeout-client: "600s"
    haproxy-ingress.github.io/timeout-server: "600s"
    haproxy-ingress.github.io/config-backend: |
      acl is_html path_reg ^/(.+)\.html$
      acl needs_html path_reg ^/([^./]+/)*[^./]+$
      http-request redirect code 301 prefix %[path,regsub(\.html$,,)] if is_html
      http-request set-path %[path].html if needs_html
spec:
  ingressClassName: haproxy-public
  tls:
    - hosts:
        - rcrumana.xyz
      secretName: rcrumana-xyz-tls
  rules:
    - host: rcrumana.xyz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: portfolio
                port:
                  number: 80
