apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vllm
resources:
  - vllm-statefulset.yaml
  - librechat-deployment.yaml
  - mongo-statefulset.yaml
  - postgres-statefulset.yaml
  - pvc.yaml
  - service.yaml
  - ingress.yaml
  - configmap-librechat.yaml
  - pdb.yaml
  - hpa-librechat.yaml

commonLabels:
  app.kubernetes.io/name: vllm-stack
  app.kubernetes.io/managed-by: argocd
