apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nextcloud

resources:
  - pvc.yaml
  - migrate-nextcloud-appdata.yaml
  - migrate-nextcloud-postgresql-data.yaml
  - migrate-nextcloud-redis-data.yaml
