apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: headscale-api
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    haproxy-ingress.github.io/backend-protocol: "http"
    haproxy-ingress.github.io/ssl-redirect: "true"
    haproxy-ingress.github.io/whitelist-source-range: "192.168.0.0/16,172.16.0.0/12,10.0.0.0/8,100.64.0.0/10"
spec:
  ingressClassName: haproxy-restricted
  tls:
    - hosts:
        - headscale.rcrumana.xyz
      secretName: headscale-tls
  rules:
    - host: headscale.rcrumana.xyz
      http:
        paths:
          - path: /register
            pathType: Prefix
            backend:
              service:
                name: headscale
                port:
                  number: 80
          - path: /machine
            pathType: Prefix
            backend:
              service:
                name: headscale
                port:
                  number: 80
          - path: /key
            pathType: Prefix
            backend:
              service:
                name: headscale
                port:
                  number: 80
          - path: /apple
            pathType: Prefix
            backend:
              service:
                name: headscale
                port:
                  number: 80
          - path: /android
            pathType: Prefix
            backend:
              service:
                name: headscale
                port:
                  number: 80
          - path: /windows
            pathType: Prefix
            backend:
              service:
                name: headscale
                port:
                  number: 80
          - path: /login
            pathType: Prefix
            backend:
              service:
                name: headscale
                port:
                  number: 80
          - path: /oidc
            pathType: Prefix
            backend:
              service:
                name: headscale
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: headscale
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: headscale-ui
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    haproxy-ingress.github.io/backend-protocol: "http"
    haproxy-ingress.github.io/ssl-redirect: "true"
    haproxy-ingress.github.io/whitelist-source-range: "192.168.0.0/16,172.16.0.0/12,10.0.0.0/8,100.64.0.0/10"
spec:
  ingressClassName: haproxy-restricted
  tls:
    - hosts:
        - headscale.rcrumana.xyz
      secretName: headscale-tls
  rules:
    - host: headscale.rcrumana.xyz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: headscale-ui
                port:
                  number: 80
