apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: homarr-helm

resources:
  - mysql-service.yaml
  - mysql-statefulset.yaml
  - redis-service.yaml
  - redis-statefulset.yaml
  - migrate-homarr-mysql-data.yaml
  - migrate-homarr-redis-data.yaml
