apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: immich

resources:
  - server-deployment.yaml
  - ml-deployment.yaml
  - redis-deployment.yaml
  - postgres-deployment.yaml
  - services.yaml
  - configmap.yaml
  - ingress.yaml
  - pvc.yaml

commonLabels:
  app.kubernetes.io/name: immich
  app.kubernetes.io/managed-by: argocd